2024-01-06 22:26:44 - 96:werkzeug:30 -  * Debugger is active!
2024-01-06 22:26:44 - 96:werkzeug:20 -  * Debugger PIN: 119-753-622
2024-01-06 22:27:02 - 35:root:20 - GET data for partner_pk: 6917ac1c-576c-4aad-9be8-1a2e65860262; {2: 3}
2024-01-06 22:27:02 - 96:werkzeug:20 - 172.20.0.1 - - [06/Jan/2024 22:27:02] "GET /api/v1/partner/6917ac1c-576c-4aad-9be8-1a2e65860262 HTTP/1.1" 200 -
2024-01-06 22:27:02 - 96:werkzeug:40 - Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.12/site-packages/werkzeug/serving.py", line 326, in execute
    write(data)
  File "/usr/local/lib/python3.12/site-packages/werkzeug/serving.py", line 294, in write
    assert isinstance(data, bytes), "applications must write bytes"
AssertionError: applications must write bytes
2024-01-06 22:28:02 - 96:werkzeug:20 -  * Detected change in '/app/app.py', reloading
